version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: corp-db
    environment:
      POSTGRES_DB: corp_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-corp-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres-corp-data:
    driver: local
